EV5WarmupCooldowndraft
TeamBasedInquiryLearning/linear-algebra pull request #376
Opened 2024-05-10 15:54 UTC by jkostiuk

Here's a draft of warmup/cooldown for EV5, addressing #370 

Largely focussed on definitions and analogy.

2024-05-15 23:30 UTC, StevenClontz commented on source/02-EV/05.ptx
> +            </task>
```suggestion
            <task>
                <statement>
                    <p>
                        Identify some ingredients in <m>S</m> that make the set linearly dependent.
                    </p>
                </statement>
            </task>
```

Fixes the issue that the question right now just prompts students to say "independent" or "dependent", and that the answer "dependent" is given away in the next task.

2024-05-15 23:41 UTC, StevenClontz requested changes
Cool stuff! Consider my suggestion above before we merge this.

2024-05-16 12:39 UTC, jkostiuk commented
ok, I agreed with the change and clicked on "commit suggestion" but it still shows "changes requested" on my end. Let me know if I'm missing something in the process.

2024-05-16 13:41 UTC, StevenClontz approved these changes

2024-05-16 13:41 UTC, merged